# Generated by Django 5.0.7 on 2025-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets_bah", "0014_remove_utilisateurprofile_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("discipline", models.CharField(blank=True, max_length=150)),
                ("lieu", models.CharField(blank=True, max_length=150)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="sports")),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
    ]
