# Generated by Django 5.0.7 on 2025-10-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets_bah", "0015_sportevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
